apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.90
  ports:
    - port: 25565
  selector:
    app: minecraft-server
